export const LOCALIZATION_KEYS = {
  auth: {
    register_success: "auth.register_success",
    login_success: "auth.login_success",
    refresh_success: "auth.refresh_success",
    logout_success: "auth.logout_success",
    logout_all_success: "auth.logout_all_success",
    invalid_credentials: "auth.invalid_credentials",
    invalid_token: "auth.invalid_token",
    token_expired: "auth.token_expired",
    token_revoked: "auth.token_revoked",
    user_blocked: "auth.user_blocked",
    user_deleted: "auth.user_deleted",
    missing_token: "auth.missing_token",
    session_not_found: "auth.session_not_found",
  },
  session: {
    created: "session.created",
    deleted: "session.deleted",
    device_not_found: "session.device_not_found",
    all_sessions_deleted: "session.all_sessions_deleted",
  },
  audit: {
    user_created: "audit.user.created",
    user_updated: "audit.user.updated",
    user_deleted: "audit.user.deleted",
    user_blocked: "audit.user.blocked",
    user_roles_assigned: "audit.user.roles_assigned",
    order_created: "audit.order.created",
    order_updated: "audit.order.updated",
    order_deleted: "audit.order.deleted",
    order_cancelled: "audit.order.cancelled",
    order_assigned: "audit.order.assigned",
    courier_verified: "audit.courier.verified",
    role_created: "audit.role.created",
    role_updated: "audit.role.updated",
  },
  user: {
    not_found: "user.not_found",
    already_deleted: "user.already_deleted",
    created: "user.created",
    updated: "user.updated",
    deleted: "user.deleted",
    roles_assigned: "user.roles_assigned",
  },
  order: {
    not_found: "order.not_found",
    created: "order.created",
    updated: "order.updated",
    deleted: "order.deleted",
    cancelled: "order.cancelled",
    assigned: "order.assigned",
    started: "order.started",
    completed: "order.completed",
    invalid_status_transition: "order.invalid_status_transition",
    already_assigned: "order.already_assigned",
    already_deleted: "order.already_deleted",
    not_assigned_to_you: "order.not_assigned_to_you",
    not_in_assigned_status: "order.not_in_assigned_status",
    not_in_progress: "order.not_in_progress",
    cannot_cancel: "order.cannot_cancel",
  },
  address: {
    not_found: "address.not_found",
    already_deleted: "address.already_deleted",
    created: "address.created",
    updated: "address.updated",
    deleted: "address.deleted",
    forbidden: "address.forbidden",
  },
  courier: {
    not_found: "courier.not_found",
    profile_not_found: "courier.profile_not_found",
    profile_updated: "courier.profile_updated",
    verified: "courier.verified",
    invalid_verification_status: "courier.invalid_verification_status",
  },
  role: {
    created: "role.created",
    not_found: "role.not_found",
    invalid_role_ids: "role.invalid_role_ids",
  },
  common: {
    bad_request: "common.bad_request",
    forbidden: "common.forbidden",
    not_found: "common.not_found",
    conflict: "common.conflict",
    internal_error: "common.internal_error",
    validation_error: "common.validation_error",
    rate_limit_exceeded: "common.rate_limit_exceeded",
    missing_permission: "common.missing_permission",
    invalid_user_type: "common.invalid_user_type",
  },
  gamification: {
    level_achieved: "gamification.level_achieved",
    points_earned: "gamification.points_earned",
    streak_updated: "gamification.streak_updated",
    streak_reset: "gamification.streak_reset",
    feature_unlocked: "gamification.feature_unlocked",
    feature_access_revoked: "gamification.feature_access_revoked",
    level_not_found: "gamification.level_not_found",
    feature_not_found: "gamification.feature_not_found",
  },
  webhook: {
    created: "webhook.created",
    updated: "webhook.updated",
    deleted: "webhook.deleted",
    test_sent: "webhook.test_sent",
    delivery_failed: "webhook.delivery_failed",
    not_found: "webhook.not_found",
  },
  flag: {
    created: "flag.created",
    updated: "flag.updated",
    deleted: "flag.deleted",
    not_found: "flag.not_found",
  },
  sandbox: {
    mode_active: "sandbox.mode_active",
    invalid_mode: "sandbox.invalid_mode",
    write_not_allowed: "sandbox.write_not_allowed",
  },
} as const;

export const L = LOCALIZATION_KEYS;
