export const LOCALIZATION_KEYS = {
  auth: {
    register_success: "auth.register_success",
    login_success: "auth.login_success",
    refresh_success: "auth.refresh_success",
    logout_success: "auth.logout_success",
    logout_all_success: "auth.logout_all_success",
    invalid_credentials: "auth.invalid_credentials",
    invalid_token: "auth.invalid_token",
    token_expired: "auth.token_expired",
    token_revoked: "auth.token_revoked",
    user_blocked: "auth.user_blocked",
    user_deleted: "auth.user_deleted",
    missing_token: "auth.missing_token",
    session_not_found: "auth.session_not_found",
  },
  user: {
    not_found: "user.not_found",
    already_deleted: "user.already_deleted",
    created: "user.created",
    updated: "user.updated",
    deleted: "user.deleted",
    roles_assigned: "user.roles_assigned",
  },
  order: {
    not_found: "order.not_found",
    created: "order.created",
    updated: "order.updated",
    deleted: "order.deleted",
    cancelled: "order.cancelled",
    assigned: "order.assigned",
    started: "order.started",
    completed: "order.completed",
    invalid_status_transition: "order.invalid_status_transition",
    already_assigned: "order.already_assigned",
    already_deleted: "order.already_deleted",
    not_assigned_to_you: "order.not_assigned_to_you",
    not_in_assigned_status: "order.not_in_assigned_status",
    not_in_progress: "order.not_in_progress",
    cannot_cancel: "order.cannot_cancel",
  },
  address: {
    not_found: "address.not_found",
    created: "address.created",
    updated: "address.updated",
    deleted: "address.deleted",
    forbidden: "address.forbidden",
  },
  courier: {
    not_found: "courier.not_found",
    profile_not_found: "courier.profile_not_found",
    profile_updated: "courier.profile_updated",
    verified: "courier.verified",
    invalid_verification_status: "courier.invalid_verification_status",
  },
  role: {
    created: "role.created",
    not_found: "role.not_found",
    invalid_role_ids: "role.invalid_role_ids",
  },
  common: {
    bad_request: "common.bad_request",
    forbidden: "common.forbidden",
    not_found: "common.not_found",
    conflict: "common.conflict",
    internal_error: "common.internal_error",
    validation_error: "common.validation_error",
    rate_limit_exceeded: "common.rate_limit_exceeded",
    missing_permission: "common.missing_permission",
    invalid_user_type: "common.invalid_user_type",
  },
} as const;

export const L = LOCALIZATION_KEYS;
